import Head from 'next/head';
import type { FormEvent, ChangeEvent } from 'react';
import { useState } from 'react';

import styles from '@/styles/Home.module.css';
import { trpc } from '../utils/trpc';

export default function Delete() {
  const [inputValue, setInputValue] = useState('');
  const { isError, isLoading, isSuccess, failureReason, mutate, data } =
    trpc.tubeStationsDelete.useMutation();

  const handleChange = (event: ChangeEvent<HTMLInputElement>): void => {
    setInputValue(event.currentTarget.value);
  };
  const handleSubmit = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    mutate({ name: inputValue });
  };

  return (
    <>
      <Head>
        <title>Delete</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={handleSubmit}>
          <h1>Delete</h1>
          <label htmlFor="stations">Search</label>{' '}
          <input name="stations" onChange={handleChange} value={inputValue} />
          <div>
            {isLoading && <p>Loading</p>}
            {isError && <p>Error: {failureReason?.message ?? 'Error'}</p>}
            {isSuccess && (
              <p>
                <code>{JSON.stringify(data)}</code>
              </p>
            )}
          </div>
          <button type="submit">Search value</button>
        </form>
      </main>
    </>
  );
}
