import Head from 'next/head';
import type { MouseEvent } from 'react';

import styles from '@/styles/Home.module.css';
import { trpc } from '../utils/trpc';

export default function Read() {
  const stationsQuery = trpc.tubeStationsRead.useQuery();
  const { isError, isLoading, isSuccess, failureReason, refetch } = stationsQuery;

  const handleClick = async (event: MouseEvent<HTMLButtonElement>): Promise<void> => {
    event.preventDefault();
    await refetch();
  };

  return (
    <>
      <Head>
        <title>Delete</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Read</h1>
        <div>
          {isLoading && <p>Loading</p>}
          {isError && <p>Error: {failureReason?.message ?? 'Error'}</p>}
          {isSuccess && (
            <p>
              <code>{JSON.stringify(stationsQuery.data)}</code>
            </p>
          )}
        </div>
        <button type="button" onClick={handleClick}>
          List values
        </button>
      </main>
    </>
  );
}
